#!/bin/bash
# get fridge temp and gpio state

source /home/pi/carfridge/code/dao/temperatureSensorDao


getTempInDeci(){
 thous=$1
 wholes="$((thous / 1000))"
 decis=$((thous - (wholes * 1000)))

 if [ $decis -lt 10 ]; then
  decis="00${decis}"
 elif [ $decis -lt 100 ]; then
  decis="0${decis}"
 fi

 echo "${wholes}.${decis}"
}

getFridge(){
 t=$(temp "fridge")
 getTempInDeci t
}

getAmbient(){
 t=$(temp "ambient")
 getTempInDeci t
}

getCompressor(){
state=$(cat /sys/class/gpio/gpio23/value)
if [ $state = "0" ]; then
 echo "off"
elif [ $state = "1" ]; then
 echo "on"
fi
}

echo "fridge $(getFridge)C, compressor $(getCompressor). (ambient $(getAmbient)C)"
#echo "$(temp fridge)"

 
