#!/bin/bash
# get fridge temp and gpio state

source /home/pi/carfridge/code/dao/temperatureSensorDao

getFridge(){
 thous=$(temp "fridge")
 wholes="$((thous / 1000))"
 decis=$((thous - (wholes * 1000)))

 if [ $decis -lt 10 ]; then
  decis="00${decis}"
 fi

 if [ $decis -lt 100 ]; then
  decis="0${decis}"
 fi

 echo "${wholes}.${decis}"
}

getCompressor(){
state=$(cat /sys/class/gpio/gpio23/value)
if [ $state = "0" ]; then
 echo "off"
elif [ $state = "1" ]; then
 echo "on"
fi
}

echo "fridge $(getFridge)C, compressor $(getCompressor)"
#echo "$(temp fridge)"

 
